name: Trigger Release

on:
  push:
    branches:
      - release

jobs:
  trigger-release:
    name: Trigger Release
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Github Event
        run: "curl -v -H \"Accept: application/vnd.github.everest-preview+json\" -H \"Authorization: token ${GITHUB_TOKEN_WORKAROUND}\" https://api.github.com/repos/arianacosta/poetic/dispatches -d '{ \"event_type\": \"semantic-release\" }'"
